name: Build Mac App with py2app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app openpyxl python-docx PyMuPDF

      - name: Build .app with py2app
        run: |
          python setup.py py2app

      - name: Archive .app
        run: |
          zip -r quiz_to_json_mac_app.zip dist/*.app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: quiz_to_json_mac_app
          path: quiz_to_json_mac_app.zip
